version: "3"

# Pi-Hole Image
# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md
#
# Unbound image
# https://github.com/MatthewVance/unbound-docker
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp" #DNS
      - "53:53/udp" #DNS
      #- "67:67/udp" #DHCP
      - "10.11.0.3:80:80/tcp" # Web Interface
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    environment:
      TZ: 'Europe/Moscow'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    restart: unless-stopped
